#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
: "${DEVKITPRO:?Set DEVKITPRO}"
: "${DEVKITPPC:?Set DEVKITPPC}"
make BUILD=build-r1276-ui TARGET=PCSX2-Wii-R1276-Menu-Interpreter EXTRA_CFLAGS="-DPCSX2WII_JIT_DISABLE -DPCSX2WII_FAST" -j1
make BUILD=build-r1276-ui-jit TARGET=PCSX2-Wii-R1276-Menu-JIT EXTRA_CFLAGS="-DPCSX2WII_FAST" -j1
