#!/bin/sh
set -eu
: "${DEVKITPRO:?Set DEVKITPRO to the supplied SDK root}"
: "${DEVKITPPC:?Set DEVKITPPC}"
cd "$(dirname "$0")/.."
make -j4 TARGET=Gekko2-R1337-Optimized BUILD=build-r1337-optimized EXTRA_CFLAGS='-DGEKKO2_EE_BLOCK_FAST -DGEKKO2_GOURAUD_EARLY_DEGENERATE'
make -j4 TARGET=Gekko2-R1337-Control BUILD=build-r1337-control EXTRA_CFLAGS='-DGEKKO2_EE_BLOCK_FAST -DGEKKO2_GOURAUD_EARLY_DEGENERATE -DGEKKO2_CACHE_LEGACY_DEFAULT'
