#!/bin/sh
set -eu
: "${DEVKITPRO:?Set DEVKITPRO}"
: "${DEVKITPPC:?Set DEVKITPPC}"
cd "$(dirname "$0")/.."
make -j4 TARGET=Gekko2-R1341 BUILD=build-r1341 EXTRA_CFLAGS='-DGEKKO2_EE_BLOCK_FAST -DGEKKO2_GOURAUD_EARLY_DEGENERATE -DGEKKO2_ARM_BETA'
