"""Rasterize DejaVu Sans Mono into 4-bit coverage at the actual UI sizes.
Runtime needs no font parser. License: docs/licenses/DejaVu.txt.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import argparse,hashlib
p=argparse.ArgumentParser();p.add_argument('--font',default='/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf');a=p.parse_args()
fontpath=Path(a.font);output=Path(__file__).resolve().parents[1]/'include/core/hw/frontend_font_data.h'
parts=['/* Generated by tools/generate_frontend_font_r1276.py. DejaVu license in docs/licenses/DejaVu.txt. */',f'/* Font SHA256: {hashlib.sha256(fontpath.read_bytes()).hexdigest()} */','#ifndef FRONTEND_FONT_DATA_H','#define FRONTEND_FONT_DATA_H','#include <stdint.h>']
for index,(w,h,size) in enumerate(((8,14,13),(24,42,39))):
 font=ImageFont.truetype(str(fontpath),size)
 boxes=[font.getbbox(chr(c)) for c in range(33,127)]
 top=min(b[1] for b in boxes);bottom=max(b[3] for b in boxes)
 offset=(h-(bottom-top))//2-top
 parts.append(f'static const uint8_t frontend_font_{index}[95][{w*h//2}]={{')
 for c in range(32,127):
  im=Image.new('L',(w,h));ImageDraw.Draw(im).text((0,offset),chr(c),font=font,fill=255,stroke_width=0)
  raw=[(v*15+127)//255 for v in im.getdata()];packed=[(raw[i]<<4)|raw[i+1] for i in range(0,len(raw),2)]
  parts.append('{'+','.join(map(str,packed))+'},')
 parts.append('};')
parts+=['#endif'];output.write_text('\n'.join(parts)+'\n')
